schema: graphql/schema.graphql
# We would like to keep subscriptions code near the handlers definition, so we have to
# add new paths to list of files scanned for GraphQL queries
documents: [graphql/**/*.graphql, src/pages/api/webhooks/saleor/**/*.ts]
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        config:
          dedupeFragments: true
        plugins:
          - typescript
          - typescript-operations
          - urql-introspection
          - typescript-urql:
              documentVariablePrefix: "Untyped"
              fragmentVariablePrefix: "Untyped"
          - typed-document-node
      generated/schema.graphql:
        plugins:
          - schema-ast
